rename next4 script to next3

diff --git a/next3 b/next3
--- a/next3
+++ b/next3
@@ -1,14 +1,14 @@
 #!/bin/sh
 #
+# NEXT3(R) snapshot management script
+#
 # Written by Amir Goldstein <amir73il@users.sf.net>, 2008
 # Copyright (C) 2008-2010 CTERA Networks
-#
-# Next4 snapshot management script
 #
 
 SCRIPT_NAME=$(basename $0)
 SCRIPT_VER=1.0.13-5
-SCRIPT_DESC="Next4 snapshot management script"
+SCRIPT_DESC="$FSTYPE snapshot management script"
 # fs/module name = script name
 FSTYPE=$SCRIPT_NAME
 
@@ -49,30 +49,30 @@ done
 
 if [ $# -ge 2 ] && [ $1 != help ] && [ $1_$2 != $1_help ] && [ $1 != config ] && \
 	[ $1 != version ] && [ $1 != debug ] && [ $1 != delay ] && [ _$1 != _test ] && [ $1 != tests ] ; then
-	# parse [[next-mount@]snapshot-name] or next4-mount or next4-device argument
+	# parse [[next-mount@]snapshot-name] or $FSTYPE-mount or $FSTYPE-device argument
 	s=$( echo $2 | ( IFS=$IFS@ ; read a b ; echo $b ) )
 	if [ -z $s ] ; then
-		# check if argument is a next4 mount point
+		# check if argument is a $FSTYPE mount point
 		dev=$( cat /proc/mounts | while read a b c d ; do ( [ _$b = _$2 ] && [ _$c = _$FSTYPE ] && echo $a ) ; done )
 		if [ ! -z $dev ] ; then
-			# found next4 mount point
-			NEXT4MNT=$2
-			NEXT4DEV=$dev
+			# found $FSTYPE mount point
+			ROOTMNT=$2
+			ROOTDEV=$dev
 		elif [ -b $2 ] || [ $1 = mkfs ] || [ $1 = on ] || [ $1 = off ] ; then
-			# argument is a next4 block device
-			NEXT4DEV=$2
-			NEXT4MNT=$3
+			# argument is a $FSTYPE block device
+			ROOTDEV=$2
+			ROOTMNT=$3
 		else
-			# snapshot name was given without next4 mount point
+			# snapshot name was given without $FSTYPE mount point
 			s=$2
 		fi
 	else
-		# snapshot name is prepended with next4 mount point
-		NEXT4MNT=$( echo $2 | ( IFS=$IFS@ ; read a b ; echo $a ) )
-		# find next4 block device from next4 mount point
-		NEXT4DEV=$( cat /proc/mounts | while read a b c d ; do ( [ _$b = _$NEXT4MNT ] && [ _$c = _$FSTYPE ] && echo $a ) ; done )
-		if [ -z $NEXT4DEV ] ; then
-			echo "$0 $1 $2: $NEXT4MNT is not a mounted $FSTYPE filesystem!"
+		# snapshot name is prepended with $FSTYPE mount point
+		ROOTMNT=$( echo $2 | ( IFS=$IFS@ ; read a b ; echo $a ) )
+		# find $FSTYPE block device from $FSTYPE mount point
+		ROOTDEV=$( cat /proc/mounts | while read a b c d ; do ( [ _$b = _$ROOTMNT ] && [ _$c = _$FSTYPE ] && echo $a ) ; done )
+		if [ -z $ROOTDEV ] ; then
+			echo "$0 $1 $2: $ROOTMNT is not a mounted $FSTYPE filesystem!"
 			exit 1
 		fi
 		# strip / from snapshot name
@@ -105,59 +105,59 @@ else
 	test_read=0
 fi
 
-# read next4 block device and mount point from conf file
+# read $FSTYPE block device and mount point from conf file
 CONFFILE=.$FSTYPE.conf
 
 # look for snapshot config file in current then home directory
-if [ -z $NEXT4DEV ] && [ -z $NEXT4MNT ] ; then
+if [ -z $ROOTDEV ] && [ -z $ROOTMNT ] ; then
 	if [ -f ./$CONFFILE ] ; then
 		. ./$CONFFILE
 	elif [ -f ~/$CONFFILE ] ; then
 		. ~/$CONFFILE
 	elif [ $( mount -t $FSTYPE | grep -v noload | wc -l ) = 1 ] ; then
-		# exactly one mounted next4 filesystem found (mounted snapshots excluded)
-		NEXT4DEV=$( mount -t $FSTYPE | grep -v noload | ( read a b c d ; echo $a ) )
-		NEXT4MNT=$( mount -t $FSTYPE | grep -v noload | ( read a b c d ; echo $c ) )
+		# exactly one mounted $FSTYPE filesystem found (mounted snapshots excluded)
+		ROOTDEV=$( mount -t $FSTYPE | grep -v noload | ( read a b c d ; echo $a ) )
+		ROOTMNT=$( mount -t $FSTYPE | grep -v noload | ( read a b c d ; echo $c ) )
 	fi
 fi
 
 if [ ! -z $1 ] && [ $1 != help ] && [ $1_$2 != $1_help ] && [ $1 != config ] && \
 	[ $1 != version ] && [ $1 != debug ] && [ $1 != delay ] && [ _$1 != _test ] && [ $1 != tests ] ; then
 	if [ $1 != mkfs ] && [ $1 != fsck ] && [ $1 != on ] && [ $1 != off ] ; then
-	if [ -z $NEXT4MNT ] ; then
-		echo "$0: ambigous or missing next4 mount point"
+	if [ -z $ROOTMNT ] ; then
+		echo "$0: ambigous or missing $FSTYPE mount point"
 		echo "run '$0 config' to set default value"
 		exit 1
 	fi
-	if [ ! -d $NEXT4MNT ] ; then
-		echo "$0: bad next4 mount point $NEXT4MNT"
+	if [ ! -d $ROOTMNT ] ; then
+		echo "$0: bad $FSTYPE mount point $ROOTMNT"
 		exit 1
 	fi
 	else
-	if [ -z $NEXT4DEV ] ; then
-		echo "$0: ambigous or missing next4 block device"
+	if [ -z $ROOTDEV ] ; then
+		echo "$0: ambigous or missing $FSTYPE block device"
 		echo "run '$0 config' to set default value"
 		exit 1
 	fi
-	if [ ! -b $NEXT4DEV ] && [ ! -f $NEXT4DEV ] ; then
-		echo "$0: bad next4 block device $NEXT4DEV"
+	if [ ! -b $ROOTDEV ] && [ ! -f $ROOTDEV ] ; then
+		echo "$0: bad $FSTYPE block device $ROOTDEV"
 		exit 1
 	fi
 	fi
-	export NEXT4MNT
-	export NEXT4DEV
-	S=$NEXT4MNT@$s
+	export ROOTMNT
+	export ROOTDEV
+	S=$ROOTMNT@$s
 fi
 
 if [ -z $SNAPDIR ] ; then
-	# directory inside next4 filesystem to store snapshot files
-	SNAPDIR=$NEXT4MNT/.snapshots
+	# directory inside $FSTYPE filesystem to store snapshot files
+	SNAPDIR=$ROOTMNT/.snapshots
 fi
 if [ -z $SNAPMNT ] ; then
 	# directory prefix for snapshot mount points
 	# snaphot mount points will be created as $SNAPMNT<snapshot-name>
 	# default to ZFS snapshot naming convention <filesystem>@<snapshot>
-	SNAPMNT=$NEXT4MNT@
+	SNAPMNT=$ROOTMNT@
 fi
 TESTDIR=test
 
@@ -173,7 +173,7 @@ case "$1" in
 	;;
   version)
 	if [ $1_$2 = $1_help ] ; then
-		echo "$1: display next4 snapshot version."
+		echo "$1: display $FSTYPE snapshot version."
 		exit 0
 	fi
 	ver=$(cat $SNAPDEBUGDIR/snapshot-version)
@@ -223,12 +223,12 @@ case "$1" in
 	echo test-$2-delay = $ms msec
 	;;
 
-# Next4 filesystem commands
+# $FSTYPE filesystem commands
   config)
 	if [ $1_$2 = $1_help ] ; then
 		echo "$1: configure or print default next filesystem parameters."
 		echo "creates configuration file $CONFFILE in current directory."
-		echo "usage: $0 config [next4-device next4-mount]"
+		echo "usage: $0 config [$FSTYPE-device $FSTYPE-mount]"
 		exit 0
 	fi
 	if [ ! -z $2 ] && [ ! -b $2 ] && [ ! -f $2 ] ; then
@@ -240,8 +240,8 @@ case "$1" in
 		exit 1
 	fi
 	if [ ! -z $2 ] && [ ! -z $3 ] ; then
-		echo NEXT4DEV=$2 > $CONFFILE
-		echo NEXT4MNT=$3 >> $CONFFILE
+		echo ROOTDEV=$2 > $CONFFILE
+		echo ROOTMNT=$3 >> $CONFFILE
 	fi
 	test -f $CONFFILE && cat $CONFFILE
 	;;
@@ -249,48 +249,48 @@ case "$1" in
 	if [ $1_$2 = $1_help ] ; then
 		echo "on: add the snapshot feature to an existing ext3 filesystem."
 		echo "after adding the snapshot feature to an ext3 filesystem, the filesystem"
-		echo "can no longer be mounted as ext3 read-write (only as next4 or ext3 read-only)."
-		echo "usage: $0 on [next4-device]"
+		echo "can no longer be mounted as ext3 read-write (only as $FSTYPE or ext3 read-only)."
+		echo "usage: $0 on [$FSTYPE-device]"
 		exit 0
 	fi
-	$TUNEFS -e remount-ro -O has_snapshot $NEXT4DEV || exit 1
-	echo snapshot feature added to $NEXT4DEV
+	$TUNEFS -e remount-ro -O has_snapshot $ROOTDEV || exit 1
+	echo snapshot feature added to $ROOTDEV
 	echo .
 	;;
   off)
 	if [ $1_$2 = $1_help ] ; then
-		echo "off: remove the snapshot feature from a next4 filesystem."
+		echo "off: remove the snapshot feature from a $FSTYPE filesystem."
 		echo "after removing the snapshot feature, all existing snapshots will be discarded"
 		echo "and the filesystem could be mounted as ext3 read-write again."
-		echo "usage: $0 off [next4-device]"
+		echo "usage: $0 off [$FSTYPE-device]"
 		exit 0
 	fi
-	$TUNEFS -O ^has_snapshot $NEXT4DEV || exit 1
-	echo snapshot feature removed from $NEXT4DEV
+	$TUNEFS -O ^has_snapshot $ROOTDEV || exit 1
+	echo snapshot feature removed from $ROOTDEV
 	echo .
 	;;
   mkfs)
 	if [ $1_$2 = $1_help ] ; then
-		echo "$1: create a next4 filesystem."
-		echo "usage: $0 mkfs [next4-device]"
+		echo "$1: create a $FSTYPE filesystem."
+		echo "usage: $0 mkfs [$FSTYPE-device]"
 		exit 0
 	fi
-	$MKFS -b 4096 -j -J big -O has_snapshot,exclude_inode $NEXT4DEV || exit 1
-	$TUNEFS -e remount-ro $NEXT4DEV
-	echo next4 filesystem created on $NEXT4DEV
+	$MKFS -b 4096 -j -J big -O has_snapshot,exclude_inode $ROOTDEV || exit 1
+	$TUNEFS -e remount-ro $ROOTDEV
+	echo $FSTYPE filesystem created on $ROOTDEV
 	echo .
 	;;
 
   stat)
 	if [ $1_$2 = $1_help ] ; then
-		echo "stat: display status of next4 filesystem and all its snapshots."
+		echo "stat: display status of $FSTYPE filesystem and all its snapshots."
 		echo "snapshot attributes are displayed in short format. to display"
 		echo "attributes in long format use the '$0 lsattr' command."
 		echo "usage: $0 stat [next-mount]"
 		exit 0
 	fi
-	echo "Mounted next4 filesystem and snapshots:"
-	df -h $NEXT4MNT $SNAPMNT* 2> /dev/null
+	echo "Mounted $FSTYPE filesystem and snapshots:"
+	df -h $ROOTMNT $SNAPMNT* 2> /dev/null
 	echo .
 	echo "Snapshots list:"
 	echo "id inode attributes disk-usage mtime filename"
@@ -306,7 +306,7 @@ case "$1" in
 	;;
   lsattr)
 	if [ $1_$2 = $1_help ] ; then
-		echo "$1: display attributes of next4 snapshots in long format."
+		echo "$1: display attributes of $FSTYPE snapshots in long format."
 		echo "usage: $0 $1"
 		exit 0
 	fi
@@ -317,7 +317,7 @@ case "$1" in
   take)
 	if [ $1_$2 = $1_help ] ; then
 		echo "take: take a snapshot."
-		echo "usage: $0 take [[next-mount@]snapshot-name] (default=next4-mount@GMT-date)"
+		echo "usage: $0 take [[next-mount@]snapshot-name] (default=$FSTYPE-mount@GMT-date)"
 		exit 0
 	fi
 	mkdir -p $SNAPDIR || exit 1
@@ -325,7 +325,7 @@ case "$1" in
 	if [ -z $s ] ; then
 		# default snapshot-name is the <date-time> in shadow copy format
 		s=$( date -u +GMT-%Y.%m.%d-%H.%M.%S )
-		S=$NEXT4MNT@$s
+		S=$ROOTMNT@$s
 	fi
 	if [ -f $SNAPDIR/$s ] ; then
 		echo "$0 take: snapshot $S already exists!"
@@ -416,21 +416,21 @@ case "$1" in
   mount)
 	if [ $1_$2 = $1_help ] ; then
 		echo "mount: mount a snapshot."
-		echo "usage: $0 mount [next4-device next4-mount]"
+		echo "usage: $0 mount [$FSTYPE-device $FSTYPE-mount]"
 		echo "usage: $0 mount [next-mount@]<snapshot-name>"
 		exit 0
 	fi
 	if [ -z $s ] ; then
-		# mount next4 filesystem 
+		# mount $FSTYPE filesystem 
 		MNTOPT="-o errors=remount-ro"
 		# uncomment to enable delayed allocation 
 		#MNTOPT="$MNTOPT,nodelalloc"
-		if [ ! -z $NEXT4DEV ] && [ -f $NEXT4DEV ] ; then
+		if [ ! -z $ROOTDEV ] && [ -f $ROOTDEV ] ; then
 			MNTOPT="$MNTOPT,loop"
 		fi
-		# we may be called from mount.next4 so add -i
-		mount -t $FSTYPE -i $MNTOPT $NEXT4DEV $NEXT4MNT || exit 1
-		echo next4 filesystem is mounted on $NEXT4MNT
+		# we may be called from mount.$FSTYPE so add -i
+		mount -t $FSTYPE -i $MNTOPT $ROOTDEV $ROOTMNT || exit 1
+		echo $FSTYPE filesystem is mounted on $ROOTMNT
 	else
   		$0 enable $s || exit 1
 		if grep $SNAPMNT$s /proc/mounts ; then
@@ -446,7 +446,7 @@ case "$1" in
   umount)
 	if [ $1_$2 = $1_help ] ; then
 		echo "umount: umount a snapshot."
-		echo "usage: $0 umount [next4-mount]"
+		echo "usage: $0 umount [$FSTYPE-mount]"
 		echo "usage: $0 umount [next-mount@]<snapshot-name>"
 		exit 0
 	fi
@@ -455,10 +455,10 @@ case "$1" in
 		for s in $( ls $SNAPDIR/ 2> /dev/null ) ; do
 			$0 umount $s 2> /dev/null
 		done
-		# umount next4 filesystem 
-		# we may be called from umount.next4 so add -i
-		umount -i -d $MNTOPT $NEXT4MNT || exit 1
-		echo next4 filesystem was unmounted
+		# umount $FSTYPE filesystem 
+		# we may be called from umount.$FSTYPE so add -i
+		umount -i -d $MNTOPT $ROOTMNT || exit 1
+		echo $FSTYPE filesystem was unmounted
 	else
 		if [ -d $SNAPMNT$s ] ; then
 			umount -d $SNAPMNT$s || exit 1
@@ -492,16 +492,16 @@ case "$1" in
 	;;
   fsck)
 	if [ $1_$2 = $1_help ] ; then
-		echo "fsck: run fsck on a snapshot or next4 filesystem."
+		echo "fsck: run fsck on a snapshot or $FSTYPE filesystem."
 		echo "usage: $0 fsck [next-device]"
 		echo "usage: $0 fsck [next-mount@]<snapshot-name>"
 		exit 0
 	fi
 	if [ -z $s ] ; then
-		echo "Fscking next4 filesystem on $NEXT4DEV..."
-		$FSCK -pf -C 0 $NEXT4DEV >&2 && \
-			echo next4 filesystem on $NEXT4DEV 'is healthy' || \
-			echo next4 filesystem on $NEXT4DEV 'has errors'
+		echo "Fscking $FSTYPE filesystem on $ROOTDEV..."
+		$FSCK -pf -C 0 $ROOTDEV >&2 && \
+			echo $FSTYPE filesystem on $ROOTDEV 'is healthy' || \
+			echo $FSTYPE filesystem on $ROOTDEV 'has errors'
 	else
   		$0 enable $s || exit 1
 		echo "Fscking snapshot $S..."
@@ -516,34 +516,34 @@ case "$1" in
 	;;
 
   mktest)
-	if [ -d $NEXT4MNT/A ] ; then
+	if [ -d $ROOTMNT/A ] ; then
 		exit 0
 	fi
-	mkdir $NEXT4MNT/A
-	mkdir $NEXT4MNT/B
-	mkdir $NEXT4MNT/C
-	mkdir $NEXT4MNT/D
-	mkdir $NEXT4MNT/E
-	echo aligator > $NEXT4MNT/A/a.txt
-	echo bizon > $NEXT4MNT/B/b.txt
-	echo camel > $NEXT4MNT/C/c.txt
+	mkdir $ROOTMNT/A
+	mkdir $ROOTMNT/B
+	mkdir $ROOTMNT/C
+	mkdir $ROOTMNT/D
+	mkdir $ROOTMNT/E
+	echo aligator > $ROOTMNT/A/a.txt
+	echo bizon > $ROOTMNT/B/b.txt
+	echo camel > $ROOTMNT/C/c.txt
 	# create non-snapshot dir in snapshots dir block group
-	mkdir -p $NEXT4MNT/$TESTDIR
-	$CHATTR -x $NEXT4MNT/$TESTDIR || exit 1
+	mkdir -p $ROOTMNT/$TESTDIR
+	$CHATTR -x $ROOTMNT/$TESTDIR || exit 1
 	;;
   rmtest)
-	rm -rf $NEXT4MNT/? 2> /dev/null
-	rm -rf $NEXT4MNT/$TESTDIR 2> /dev/null
+	rm -rf $ROOTMNT/? 2> /dev/null
+	rm -rf $ROOTMNT/$TESTDIR 2> /dev/null
 	;;
   lstest)
 	if [ $1_$2 = $1_help ] ; then
-		echo "lstest: list the content of test files in a snapshot or next4 filesystem."
-		echo "usage: $0 lstest [[next-mount@]snapshot-name] (default=next4-mount)"
+		echo "lstest: list the content of test files in a snapshot or $FSTYPE filesystem."
+		echo "usage: $0 lstest [[next-mount@]snapshot-name] (default=$FSTYPE-mount)"
 		exit 0
 	fi
 	if [ -z $s ] ; then
 		echo Files in file system:
-		d=$NEXT4MNT
+		d=$ROOTMNT
 	else
 		$0 mount $s || exit 1
 		echo Files in snapshot $s:
@@ -575,7 +575,7 @@ case "$1" in
 		N=$2
 	fi
 	# disable read-ahead if test read is enabled
-	test $test_read = 0 || blockdev --setra 0 $NEXT4DEV
+	test $test_read = 0 || blockdev --setra 0 $ROOTDEV
 	for s in $( ls $SNAPDIR/ 2> /dev/null ) ; do
 		$0 delete $s 2> /dev/null
 	done
@@ -593,9 +593,9 @@ case "$1" in
         ( [ ${test_read}_ms = 0_ms ] && [ ${3}_ms != 0_ms ] ) || exit 0
 	sleep 1
 	if [ $N = 0 ] ; then
-		$0 umount $NEXT4MNT || exit 1
-		$0 fsck $NEXT4DEV
-		$0 mount $NEXT4DEV $NEXT4MNT || exit 1
+		$0 umount $ROOTMNT || exit 1
+		$0 fsck $ROOTDEV
+		$0 mount $ROOTDEV $ROOTMNT || exit 1
 	else
 		for n in $( seq 1 $N ) ; do
 			$0 fsck $n 2> /dev/null
@@ -632,7 +632,7 @@ case "$1" in
 		M=1
 	fi
 	F=${M}M
-	cd $NEXT4MNT/$TESTDIR > /dev/null
+	cd $ROOTMNT/$TESTDIR > /dev/null
 	NOTRUNC="conv=notrunc"
 	# uncomment the following line to run in-place write tests
 	INPLACE=$NOTRUNC
@@ -663,25 +663,25 @@ case "$1" in
 		echo Create test:
 		echo ------------
 		echo 'Creating d.txt'
-		echo dodo > $NEXT4MNT/D/d.txt
+		echo dodo > $ROOTMNT/D/d.txt
 		echo 'Creating e.txt'
-		echo emu > $NEXT4MNT/E/e.txt
+		echo emu > $ROOTMNT/E/e.txt
 	  ;;
 	  2)
 		echo Write test:
 		echo -----------
 		echo 'Writing b.txt (append)'
-		echo 'barracuda' >> $NEXT4MNT/B/b.txt
+		echo 'barracuda' >> $ROOTMNT/B/b.txt
 		echo 'Writing c.txt (truncate)'
-		echo 'crocodile' > $NEXT4MNT/C/c.txt
+		echo 'crocodile' > $ROOTMNT/C/c.txt
 	  ;;
 	  3)
 		echo Remove test:
 		echo ------------
 		echo "Truncating c.txt (to size $TRUNCSIZE)"
-		truncate -s $TRUNCSIZE $NEXT4MNT/C/c.txt
+		truncate -s $TRUNCSIZE $ROOTMNT/C/c.txt
 		echo 'Removing d.txt'
-		rm $NEXT4MNT/D/d.txt
+		rm $ROOTMNT/D/d.txt
 	  ;;
 	  4)
 		echo Restore test:
@@ -691,21 +691,21 @@ case "$1" in
 		if ! grep $SNAPMNT$f /proc/mounts ; then
 			$0 mount $f || exit 1
 		fi
-		rm -rf $NEXT4MNT/?
-		cp -R $SNAPMNT$f/? $NEXT4MNT/
+		rm -rf $ROOTMNT/?
+		cp -R $SNAPMNT$f/? $ROOTMNT/
 		$0 umount $f || exit 1
 	  ;;
 	  5)
 		echo Delete excluded test:
 		echo ---------------------
 	  	#echo Removing excluded files
-	  	#rm $NEXT4MNT/*M
+	  	#rm $ROOTMNT/*M
 	  ;;
 	  6)
 		echo Delete reallocated test:
 		echo ------------------------
 		#echo Removing /$F
-		#rm $NEXT4MNT/$F
+		#rm $ROOTMNT/$F
 	  ;;
 	  7)
 		echo Shrink snapshots test:
@@ -737,22 +737,22 @@ case "$1" in
 	echo "usage: $0 help [cmd]"
 	echo "usage: $0 version"
 	echo
-	echo "Next4 filesystem maintenance commands:"
-	echo "usage: $0 {config|mount} [next4-device next4-mount]"
-	echo "usage: $0 {mkfs|fsck|on|off} [next4-device]"
-	echo "usage: $0 {stat|umount} [next4-mount]"
+	echo "$FSTYPE filesystem maintenance commands:"
+	echo "usage: $0 {config|mount} [$FSTYPE-device $FSTYPE-mount]"
+	echo "usage: $0 {mkfs|fsck|on|off} [$FSTYPE-device]"
+	echo "usage: $0 {stat|umount} [$FSTYPE-mount]"
 	echo
-	echo "Next4 snapshot commands:"
+	echo "$FSTYPE snapshot commands:"
 	echo "usage: $0 take [[next-mount@]snapshot-name] (default=next-mount@GMT-date)"
 	echo "usage: $0 {mount|umount|delete|remove|fsck|dump} [next-mount@]<snapshot-name>"
 	echo
 	echo "<snapshot-name> parameter may be just the name of the snapshot or may be"
-	echo "given in ZFS style of <next4-mount>@<snapshot-name>."
-	echo "in the former case, the next4 mount point is either read from /proc/mounts"
-	echo "(if only one next4 filesystem is mounted) or from $CONFFILE config file."
-	echo "in the latter case, the next4 mount point is parsed from the snapshot name prefix."
+	echo "given in ZFS style of <$FSTYPE-mount>@<snapshot-name>."
+	echo "in the former case, the $FSTYPE mount point is either read from /proc/mounts"
+	echo "(if only one $FSTYPE filesystem is mounted) or from $CONFFILE config file."
+	echo "in the latter case, the $FSTYPE mount point is parsed from the snapshot name prefix."
 	echo
-	echo "Next4 debug and test commands:"
+	echo "$FSTYPE debug and test commands:"
 	echo "usage: $0 debug [debug-level]"
 	echo "usage: $0 delay <take|delete|cow|read|bitmap> [delay-sec] [delay-msec]"
 	echo "usage: $0 {test|tests} [test-number] [delay-sec] [file-size-mb]"
